[project]
name = "hands-on-experiments"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "groq>=0.22.0",
    "openai-agents>=0.0.8",
    "uvicorn>=0.34.0",
]
